routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('index');
});

// Route::get('/siswa', function () {
//     return view('siswa');
// });

// Route::get('/siswa', function () {
//     $nama = "Azriana";
//     return view('siswa', ['nama' => $nama]);
// });


// Route::get('/siswa', 'SiswaController@index');

Route::resource('siswa', 'SiswaController');


Route::get('/bayar', function () {
    return view('pembayaran');
});

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    protected $table = 'students';

    protected $fillable = ['nisn', 'nis', 'nama', 'kelas', 'alamat', 'no_telepon'];


    public function getClassFormattedAttribute()
    {
        $value = '';

        if($this->kelas == 0 ){
            $value = "X RPL";
        }
        if($this->kelas == 1 ){
            $value = "XI RPL";
        }
        if($this->kelas == 2 ){
            $value = "XII RPL";
        }
        
        return $value;
    }
    
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
// use Illuminate\Support\Facades\DB;
use App\Siswa;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $nama = "Azriana";
        // return view('siswa', ['nama' => $nama]);

        // Query Builder
        // $data = DB::table('siswa')->get();

        $data = Siswa::get();
        return view('siswa.index', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('siswa/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Siswa::create([
            'nisn' => $request->nisn,
            'nis' => $request->nis,
            'nama' => $request->nama,
            'kelas' => $request->kelas,
            'alamat' => $request->alamat,
            'no_telepon' => $request->telp,
        ]);

        //arahkan ke halaman siswa
        return redirect('siswa');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         //tampilkan data berdasarkan $id data
         $data = Siswa::findOrFail($id);

         //arahkan dan tampilkan data pada halaman edit
         return view('siswa.show', compact('data'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //tampilkan data berdasarkan $id data
        $data = Siswa::findOrFail($id);

        //arahkan dan tampilkan data pada halaman edit
        return view('siswa.edit', compact('data'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    
        Siswa::where('id', $id)
                ->update([
                    'nisn' => $request->nisn,
                    'nis' => $request->nis,
                    'nama' => $request->nama,
                    'kelas' => $request->kelas,
                    'alamat' => $request->alamat,
                    'no_telepon' => $request->telp,
                ]);

        return redirect('siswa');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //hapus data berdasarkan $id
        Siswa::destroy($id);

        //arahkan ke halaman siswa
        return redirect('siswa');

    }
}

resources/views/index.blade.php
@extends('layouts.main')

@section('title','Home')

@section('content')

<div class="container mt-5">
    <h1>Hello Home</h1>
</div>
    
@endsection

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>@yield('title')</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{{url('/home')}}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('siswa.index')}}">Siswa</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url('/bayar')}}">Pembayaran</a>
            </li>
          </ul>
        </div>
    </div>
</nav>

    @yield('content')

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

resources/views/pembayaran.blade.php
@extends('layouts.main')

@section('title','Pembayaran')

@section('content')

<div class="container mt-5">
    <h1>Hello Pembayaran</h1>
</div>
    
@endsection

resources/views/siswa/create.blade.php
@extends('layouts.main')
@section('title','Tambah Data')

@section('content')

<div class="container mt-5">
    <h3>Tambah Data</h3>
<form method="POST" action="{{ route('siswa.store') }}">
    @csrf
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="nisn">NISN</label>
            <input type="text" class="form-control" name="nisn" id="nisn">
          </div>
          <div class="form-group col-md-6">
            <label for="nis">NIS</label>
            <input type="text" class="form-control" name="nis" id="nis">
          </div>
        </div>

        <div class="form-group">
          <label for="nama">Nama</label>
          <input type="text" name="nama" class="form-control" id="nama">
        </div>

        <div class="form-group">
          <label for="kelas">Kelas</label>
          <select name="kelas" id="kelas" class="form-control">
              <option value="0">X RPL</option>
              <option value="1">XI RPL</option>
              <option value="2">XII RPL</option>
          </select>
        </div>

        <div class="form-group">
          <label for="alamat">Alamat</label>
          <input type="text" name="alamat" class="form-control" id="alamat">
        </div>

        <div class="form-group">
          <label for="telp">Telepon</label>
          <input type="text" name="telp" class="form-control" id="telp">
        </div>
      
        <button type="submit" class="btn btn-primary">Kirim</button>
      </form>
</div>
@endsection

resources/views/siswa/edit.blade.php
@extends('layouts.main')
@section('title','Edit Data')

@section('content')

<div class="container mt-5">
    <h3>Edit Data</h3>
<form method="POST" action="{{ "/siswa/$data->id" }}">
  @method('put')
  @csrf

        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="nisn">NISN</label>
            <input type="text" class="form-control" name="nisn" id="nisn" value="{{ $data->nisn }}">

          </div>
          <div class="form-group col-md-6">
            <label for="nis">NIS</label>
            <input type="text" class="form-control" name="nis" id="nis" value="{{ $data->nis }}">
          </div>
        </div>

        <div class="form-group">
          <label for="nama">Nama</label>
          <input type="text" name="nama" class="form-control" id="nama" value="{{ $data->nama }}">
        </div>

        <div class="form-group">
          <label for="kelas">Kelas</label>
          <select name="kelas" id="kelas" class="form-control">
              <option value="0" @if($data->kelas == 0) {{'selected'}} @endif>X RPL</option>
              <option value="1" @if($data->kelas == 1) {{'selected'}} @endif>XI RPL</option>
              <option value="2" @if($data->kelas == 2) {{'selected'}} @endif>XII RPL</option>
          </select>
        </div>

        <div class="form-group">
          <label for="alamat">Alamat</label>
          <input type="text" name="alamat" class="form-control" id="alamat" value="{{ $data->alamat }}">
        </div>

        <div class="form-group">
          <label for="telp">Telepon</label>
          <input type="text" name="telp" class="form-control" id="telp" value="{{ $data->no_telepon }}">
        </div>
      
        <button type="submit" class="btn btn-primary">Kirim</button>
      </form>
</div>
@endsection

resources/views/siswa/index.blade.php
@extends('layouts.main')

@section('title','Siswa')

@section('content')

<div class="container mt-5">
        <h1>Daftar Siswa</h1>
        <a href={{url('siswa/create')}} class="btn btn-primary btn-sm" >Tambah</a>
        
        <table class="table mt-2">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">NISN/NIS</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Kelas</th>
                    <th scope="col">Aksi</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach ($data as $dt)
                    <tr>
                        <th scope="row">{{ $loop->iteration }}</th>
                        <td>{{ $dt->nisn }} / {{ $dt->nis }}</td>
                        <td>{{ $dt->nama }}</td>
                        <td>{{ $dt->class_formatted }}</td>
                        <td>
                              <a href="{{"siswa/$dt->id/edit"}}"class="btn btn-warning btn-sm" >edit</a>
                              <form action={{"/siswa/$dt->id"}} method="POST" class="d-inline">
                                @method('delete')
                                @csrf
                                  <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Yakin?')">Hapus</button>
                              </form>
                              <a href={{"siswa/$dt->id"}} class="btn btn-primary btn-sm" >Detail</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
              </table>

</div>
    
@endsection

resources/views/siswa/show.blade.php
@extends('layouts.main')
@section('title','Detail Data')

@section('content')

<div class="container mt-5">
    <h3>Detail Data</h3>
<form method="POST" action="{{ "/siswa/$data->id" }}">
  @method('put')
  @csrf

        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="nisn">NISN</label>
            <input type="text" class="form-control" name="nisn" id="nisn" value="{{ $data->nisn }}" disabled>

          </div>
          <div class="form-group col-md-6">
            <label for="nis">NIS</label>
            <input type="text" class="form-control" name="nis" id="nis" value="{{ $data->nis }}" disabled>
          </div>
        </div>

        <div class="form-group">
          <label for="nama">Nama</label>
          <input type="text" name="nama" class="form-control" id="nama" value="{{ $data->nama }}" disabled>
        </div>

        <div class="form-group">
          <label for="kelas">Kelas</label>
          <select name="kelas" id="kelas" class="form-control" disabled>
              <option value="0" @if($data->kelas == 0) {{'selected'}} @endif>X RPL</option>
              <option value="1" @if($data->kelas == 1) {{'selected'}} @endif>XI RPL</option>
              <option value="2" @if($data->kelas == 2) {{'selected'}} @endif>XII RPL</option>
          </select>
        </div>

        <div class="form-group">
          <label for="alamat">Alamat</label>
          <input type="text" name="alamat" class="form-control" id="alamat" value="{{ $data->alamat }}" disabled>
        </div>

        <div class="form-group">
          <label for="telp">Telepon</label>
          <input type="text" name="telp" class="form-control" id="telp" value="{{ $data->no_telepon }}" disabled>
        </div>
      
      </form>
</div>
@endsection